#!/usr/bin/perl -w 
# generated by wxGlade 0.6.5 (standalone edition) on Fri Nov 30 13:55:30 2012
# To get wxPerl visit http://wxPerl.sourceforge.net/

# Change log
# 2016/03/12 added to git

use strict;
use LWP::UserAgent;
use LWP::Simple;
use HTTP::Request;
use HTTP::Headers;
use HTML::Restrict;
use HTML::Entities;
use MIME::Base64;
use DBI;
use XML::Simple qw(XMLin XMLout);
# use XML::Tidy;
use Date::Calc 'Today';
use Data::Dumper 'Dumper';			
$Data::Dumper::Sortkeys = 1;
$Data::Dumper::Terse = 0;
$Data::Dumper::Indent = 1;
use File::Copy qw(copy move);
use POSIX;
use Getopt::Std;
use Storable 'dclone';

my %opts;
getopts('i:raDI:O:A',\%opts);
# -i <ebay item ID>		- perform operations on this single item
# -a                  - perform operations on all items
# -r 									- revise item(s)
# -D                  - Debug/verbose mode. 
# -I <filename>       - Input filename. csv format (same as output. PUT NEW VALUE IN THE "TOTAL SHIPPING COST" column)
# -O <filename>       - output filename base. default is 'product_import'
my @item_list;
my $process_all_items = 0;

if ( defined $opts{i} ) {
	@item_list = split(',',$opts{i});
}
elsif ( defined $opts{a} ) {
  $process_all_items = 1;
}
else {
	die "must supply either option '-i <item id>' or '-a' option";
}

my $REVISE_ITEM = defined $opts{r} ? 1 : 0;
my $DEBUG       = defined $opts{D} ? 1 : 0;
my $infile      = defined $opts{I} ? $opts{I} : '';
my $outfile     = defined $opts{O} ? $opts{O} : 'dump';
my $ReturnAll   = defined $opts{A} ? 1 : 0;

print "\n\nGetting eBay information......\n\n";


###################################################
# EBAY API INFO                                   #
###################################################
my $devid = 'd57759d2-efb7-481d-9e76-c6fa263405ea';
my $appid = 'KenCicog-a670-43d6-ae0e-508a227f6008';   # client ID
my $certid = '8fa915b9-d806-45ef-ad4b-0fe22166b61e';  # client's secret key

my $header = HTTP::Headers->new;
$header->push_header('X-EBAY-API-COMPATIBILITY-LEVEL' => '899');
$header->push_header('X-EBAY-API-DEV-NAME'  => $devid );
$header->push_header('X-EBAY-API-APP-NAME'  => $appid);
$header->push_header('X-EBAY-API-CERT-NAME' => $certid);
$header->push_header('X-EBAY-API-CALL-NAME' => '');                                       # Supply call name to submit_request() 
$header->push_header('X-EBAY-API-SITEID'    => '0');                                      # 0 => usa
$header->push_header('Content-Type'         => 'text/xml');
$header->push_header('Authorization'        => "Basic " . MIME::Base64::encode_base64("$appid:$certid");

# eBayAuthToken
my $eBayAuthToken = 'AgAAAA**AQAAAA**aAAAAA**/89cWg**nY+sHZ2PrBmdj6wVnY+sEZ2PrA2dj6wHlIKoCZCBogmdj6x9nY+seQ**4EwAAA**AAMAAA**Qk4PPbHKGx2DPqAeO0Dumf0k2WyACkgfnG9eeB2Hiobbxd2iZ5n3I/YbPMaYduNN+JXxejyhONith2q9PNpf3ZjX2WHI/v3jkvDp64W/IGwCPSU6H9exrg/1eQECbnqaVEWuI5T+7Zv7M9zyQC9R0wphcJC6dG5R2BC96qQVlJIVzveitGchlx2whXgAWnbz5tZhnsgjsHRrXzUXGoQCbxgsmGrpKKYoSBZLvl2r4gWKFO0/iNOoDBQiLL7q00nI3wDlCODjAu6QtJqgAzRLBjNBX9TGljUP/MQLHG37kFRhSvhGBt7rPjkMaqW/CFar4GtCWP/0rK/8OUFDvGIKjhHWJ8c+UTCMtb1N83MMj+Sm8JvrpACOGKV65yKEzyvFQtG9TmL/OiPuPX7/ouRI2IHRYoJ7RKbC6u9YYtvdRBL7xsjiXbkIMlAeVxv2aeZNhaf4WaXLKCAYC8DQPjX9pE/FiM/D0B3LofIobVO79IQJz61eh1+pF2zBYWQ9bSELZLBXHsRYmPVC6b21tyBTatloDTzddVVRSqVn5eg/pW73Sq5EOmwhBYiKfp8xFkpjCRvP+VDQowetVv7XF733/RBEMUpnhzK1oyr8y5sPzpJ+uGtLzqVmARDKCYcX1xo5B046/QHpiJlxQubac80XweKguowFJP+jOh6MfqRHZtj8TNcS1XHzO3/ZAj9Mt7Wu7TFSlctG557ESJXa/rxehfQKsm3Cc3MHYE9aBPmrrweuGK/n3UMPstxPb+aqXjV/';

# eBay OAuth2 Token (expires in 5 minutes)
my $eBayOAuth2Token = 'v^1.1#i^1#p^1#I^3#r^0#f^0#t^H4sIAAAAAAAAAOVXfWwURRTv9dpKgWIiVhQJnls0RNi92dv7XLlLjpZKw8eVXm2kfDSzu7Pt2r3dY2fOcgRjaQQiKBE1QZGE4j8GEg0iWiWSGKMRJKSGqDENATQRq6JVIn7x5ez2Wq6VQIVKSLx/LvPmzZv3+73fm9kB7SWlD6ybu+73MtcthZ3toL3Q5eLHgdKS4hkT3IWTiwtAnoOrs31ae1GHu3cWhik9LdYhnDYNjDwrU7qBRccYZTKWIZoQa1g0YAphkchiMr5gvujjgJi2TGLKps54aqqijJ+HoSAEQV7yA58kqNRqDMSsN6NMRA74IJLCqiSrkirzdB7jDKoxMIEGiTI+wIdZILCArwd+kfeJQojz875GxtOALKyZBnXhABNz0hWdtVZerldOFWKMLEKDMLGaeHUyEa+pmrOwfpY3L1Ysx0OSQJLBQ0eVpoI8DVDPoCtvgx1vMZmRZYQx44317zA0qBgfSOYa0neo9qlKSAZKIAgVyMvKqDBZbVopSK6chm3RFFZ1XEVkEI1kr0YoJUN6FMkkN1pIQ9RUeey/RRmoa6qGrCgzZ3Z8cby2lonNQ0alJpvNLAyGAOsXlCALEUBsAIShzxdSgwCEc5v0R8oxPGyXStNQNJsv7FloktmIZoyG8wLyeKFOCSNhxVViZ5PvFxzgD/CNdj37C5ghLYZdUpSiJHic4dXZH1xNiKVJGYIGIwyfcOiJMjCd1hRm+KQjw5xyVuIo00JIWvR629rauDaBM61mrw8A3vvIgvlJuQWlIDPga/c61q6+gNUcKDKiK7Emkmya5rKSypQmYDQzMT4SDIMc7UOzig23/sOQB9k7tBdGqzckiZcjAu8HihqE4Yh/NJojltOn184DSTDLpqDVikhahzJiZSqzTApZmiIKAdUnhFXEKsGIyvojqspKAaphXkVUxUiS5Ej4/9IjI1V5UjbTqNbUNTk7elofDZ0LllILLZJNIl2nhpEq/rIgsQ3yBsKze30EEO0YmAaBaY2zdc3JZsprQnqe2aYmJ+vrwq3RW/CmKioF2I9UU/rvL86By+HHZM5C2MxY9ObmEvaRXm+20k4zDWKZuo6sBv66mBjlw/yGH+SXBSXrGmWx6WYD9i9OyGuUNSQ3D+KiDtd8p5wBPhIOhQKB0HVhq3RqWp+9oefVCIo618QEKf/Bd4d36PsnVuD8+A7XW6DD9QZ9QgEvuI+vAPeWuB8uco+fjDWCOA2qHNaaDfpZbyGuFWXTULMKS1xLpuze2ZT34upcBu4cfHOVuvlxeQ8wMOXSTDF/66QyPgwEwAN63wqhRlBxabaIv6Po9p6tvp83XXj+zO7CRPD+c43FD4Uqu0DZoJPLVVxApVBQeqTh6OwJT9St/e3Ias/pp5aPeWljQdXkXxuL/D3b3us9/dcfmw++O55pGnec3fNMy8Fjqw/P/XN6V6Li4vqWdSte6FM/fW7H2F2Tdn40451Zb04/f+bFpau2vvbkssqJ+zef2P/g+rb3f5quvVy3aFft0pnq8UOPlxzt7fwxASqENaf6ppZP9X+obeh7uuLA112Z1l+614xd1eTWV39Q13X2h5OtvW9v2vfd9r49W0rvPrT48IpXdgjGWeG8/9QXn294takcdmtfhZuj2w5tlDxf9rw+SenutiSyr1y5a8fyT0543eFQVfmSe87ddmDax8dOerNbzj/b89nMeabv+zFrJ15MVZdd2Fu6Pbmi7Nu93/SX72/NyWYpCw8AAA==';

my $request_getitem_default = <<END_XML;
<?xml version='1.0' encoding='utf-8'?>
<GetItemRequest xmlns="urn:ebay:apis:eBLBaseComponents">
  <RequesterCredentials>
    <eBayAuthToken>$eBayAuthToken</eBayAuthToken>
  </RequesterCredentials>
  <WarningLevel>High</WarningLevel>
  __DETAIL_LEVEL__
  <ItemID>__ItemID__</ItemID>
  <IncludeItemSpecifics>TRUE</IncludeItemSpecifics>
</GetItemRequest>
END_XML

my $request_getmyebayselling = <<END_XML;
<?xml version='1.0' encoding='utf-8'?>
<GetMyeBaySellingRequest xmlns="urn:ebay:apis:eBLBaseComponents">
<RequesterCredentials>
  <eBayAuthToken>$eBayAuthToken</eBayAuthToken>
</RequesterCredentials>
<WarningLevel>High</WarningLevel>
<ActiveList>
	<Include>true</Include>
	<Pagination>
		<EntriesPerPage>200</EntriesPerPage>
		<PageNumber>__PAGE_NUMBER__</PageNumber>
	</Pagination>
</ActiveList>
</GetMyeBaySellingRequest>
END_XML

###########################################################
# END EBAY API INFO                                       #
###########################################################

my $request;
my $response_hash;

################################################################################
# Get list of all item id's
################################################################################
my @all_items;
my $pagenumber=1;
my $maxpages=1000000;

if ( ! $process_all_items ) {
	push(@all_items,@item_list);
}
else {
  while ( $pagenumber <= $maxpages ) {
    $request = $request_getmyebayselling;
    $request =~ s/__PAGE_NUMBER__/$pagenumber/;
    $response_hash = submit_request( 'GetMyeBaySelling', $request, $header );
    for my $i ( @{$response_hash->{ActiveList}->{ItemArray}->{Item}} ) {
      push(@all_items, $i->{ItemID});
    }
    if ($pagenumber==1) {
      $maxpages = $response_hash->{ActiveList}->{PaginationResult}->{TotalNumberOfPages};
    }
    $pagenumber++;
  }
}

my $all_items_count = scalar @all_items;


################################################################################
# Loop over each item (active on eBay)
################################################################################
for my $item_id ( reverse @all_items ) {

  my @orders = getOrders();

#   # Get detailed info from ebay on this itemID
#   $request = $request_getitem_default;
#   if ( $ReturnAll ) {
#     $request =~ s#__DETAIL_LEVEL__#<DetailLevel>ReturnAll</DetailLevel>#;
#   } else {
#     $request =~ s#__DETAIL_LEVEL__##;
#   }
#   $request =~ s/__ItemID__/$item_id/;
#   my $ebayResponse = submit_request( 'GetItem', $request, $header );
#   my $ebayListing = $ebayResponse->{Item};
# 
#   print Dumper($ebayListing);
}

print "\n\n";
exit;

####################################################################################################

sub getOrders() {
	my ($call_name, $request, $objHeader) = @_;
  my $apiGetOrders = encode_entities('https://api.ebay.com/sell/fulfillment/v1/order?filter=orderfulfillmentstatus:{NOT_STARTED|IN_PROGRESS}');

	my $header->remove_header('X-EBAY-API-CALL-NAME');
#	$header->push_header('' => $call_name);

  my $requestBody ='';
  my $objUserAgent = LWP::UserAgent->new;
  my $objRequest   = HTTP::Request->new(
    "GET",
    "https://api.ebay.com/ws/api.dll",
    $objHeader,
    $requestBody
  );
}

sub submit_request {
	my ($call_name, $request, $objHeader) = @_;
  my ($objRequest, $objUserAgent, $objResponse);
  my $request_sent_attempts = 0;

	$header->remove_header('X-EBAY-API-CALL-NAME');
	$header->push_header  ('X-EBAY-API-CALL-NAME' => $call_name);

  RESEND_REQUEST:
  $request_sent_attempts++;

  # Create UserAgent and Request objects
  $objUserAgent = LWP::UserAgent->new;
  $objRequest   = HTTP::Request->new(
    "POST",
    "https://api.ebay.com/ws/api.dll",
    $objHeader,
    $request
  );

	#print "\n objHeader : ",Dumper($objHeader);
	#print "\n request   : ",Dumper($request);
	#print "\n objRequest: ",Dumper($objRequest);

  # Submit Request
  $objResponse = $objUserAgent->request($objRequest);		# SEND REQUEST

  # Parse Response object to get Acknowledgement 
	my $content =  $objResponse->content;
	my $response_hash = XMLin( "$content",  
      ForceArray=>['InternationalShippingServiceOption','ShippingServiceOptions','ShipToLocation','Variation','NameValueList', ] );
	#my $response_hash = XMLin( $content );
  my $ack = $response_hash->{Ack};

  if (!$objResponse->is_error && $ack =~ /success/i ) {
		#print "\n\n";
		#print  "Status          : Success\n";
		#print  "Object Content  :\n";
		#print  $objResponse->content;
		#print Dumper( $response_hash );

    return $response_hash;
  }
  else {
		print "\n\n";
    print  "Response msg.   : ", Dumper( $response_hash->{Errors} );
    print  "Status          : FAILED";
    print  $objResponse->error_as_HTML;

    # Resend update request
    if ( $request_sent_attempts < 1 ) {
      print  "Attempting to resend update request.\n";
      goto RESEND_REQUEST;
    }

		die;
  }

} # end submit_request()

